// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEBSei32J2bWR_fCiuX0vME32tizwiNRc',
    appId: '1:1066807239634:web:c4e26be9fd974539789e0b',
    messagingSenderId: '1066807239634',
    projectId: 'kit-store-start-ed4aa',
    authDomain: 'kit-store-start-ed4aa.firebaseapp.com',
    storageBucket: 'kit-store-start-ed4aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvyb6oWTGdX8gjI4Vy_LhF6luQDvus1j4',
    appId: '1:1066807239634:android:2ad90e50e584ec09789e0b',
    messagingSenderId: '1066807239634',
    projectId: 'kit-store-start-ed4aa',
    storageBucket: 'kit-store-start-ed4aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCexzk8D-j86eTiF-SHyJP0FCkoijNRJLE',
    appId: '1:1066807239634:ios:9afbf2310115701a789e0b',
    messagingSenderId: '1066807239634',
    projectId: 'kit-store-start-ed4aa',
    storageBucket: 'kit-store-start-ed4aa.firebasestorage.app',
    iosBundleId: 'com.example.kitStoreStart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCexzk8D-j86eTiF-SHyJP0FCkoijNRJLE',
    appId: '1:1066807239634:ios:9afbf2310115701a789e0b',
    messagingSenderId: '1066807239634',
    projectId: 'kit-store-start-ed4aa',
    storageBucket: 'kit-store-start-ed4aa.firebasestorage.app',
    iosBundleId: 'com.example.kitStoreStart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEBSei32J2bWR_fCiuX0vME32tizwiNRc',
    appId: '1:1066807239634:web:6a45d8197a888a11789e0b',
    messagingSenderId: '1066807239634',
    projectId: 'kit-store-start-ed4aa',
    authDomain: 'kit-store-start-ed4aa.firebaseapp.com',
    storageBucket: 'kit-store-start-ed4aa.firebasestorage.app',
  );
}
